stages:
  - publish
  - notice

publish-python:
  stage: publish
  before_script:
    - pip3 install build twine
  script:
    - pip3 install -r requirements.txt
    - python3 -m build --version
    - python3 -m build python/
    - twine check python/dist/*
    - twine upload python/dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - master

publish-java:
  stage: publish
  script:
    - cd java/
    - mvn clean deploy -DskipTests -s settings.xml
  only:
    - master

publish-nodejs:
  stage: publish
  script:
    - cd nodejs/
    - npm run build
    - npm publish
  only:
    - master

notice:
  stage: notice
  script:
    - chmod +x scripts/notice.sh
    - ./scripts/notice.sh
  only:
    - master